name: Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./
      - uses: actions/deploy-pages@v2
